### ISSUE TITLE
Y bar value intersect

### ISSUE THREAD

**Issue by emadhegab** [mmislam101/SimpleBarChart#3]
if the value of Y get like 20000 the labels got intersected in ugly way.. can you fix it ASAP?

**Comment by nitin-agam** [comment]
I've also faced this issue, but I've handled the incrementValue according to max value.

For eg: If maxValue is between 1-100, then incrementValue = 10
maxValue is between 100-1000, then incrementValue = 100
maxValue is between 1000-10000, then incrementValue = 1000 so on.....

Simple and best way...

Enjoy!

**Comment by mmislam101** [comment]
Yes @nitin-agam , that's my approach also
